// actionTypes.js

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const SEARCH_USERS = "SEARCH_USERS";
 
export const APPLY_FILTERS = "APPLY_FILTERS";

export const SELECT_TEAM_MEMBER = "SELECT_TEAM_MEMBER";
export const CREATE_TEAM = "CREATE_TEAM";
